title: "时间停止"
author: "@anthony"
description: ""
baseurl: ""
url: "https://moments.dongxing.xin"
email: "hello@dongxing.xin"
permalink: "/:categories/:year/:month/:day.html"
relative_permalinks: false
paginate: 20
paginate_path: "/page/:num/"
timezone: Asia/Shanghai  # A list of all available values can be found at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
cdnurl: "https://storage.dongxing.xin/moments"

highlighter: "rouge"
markdown: "kramdown"

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: posts
        values:
            title: ""

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-mentions
  - jemoji
  - jekyll-timeago
  - jekyll-hashtags

jekyll-mentions:
  base_url: https://twitter.com
